name: Build & Release Hotfixes

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag is valid
        id: validate_tag
        run: |
          regex="^v([0-9]{2}\.){4}[0-9]{2}$"
          TAG="${GITHUB_REF#refs/tags/}"
          if [[ "$TAG" =~ $regex ]]; then
            echo "The tag \"$TAG"\ is valid."
          else
            echo "The tag is not valid."
            exit 0  # Just exit without failing, to stop the workflow here
          fi

      - name: Check if release exists
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Checking if release exists for tag: $TAG_NAME"
          
          RELEASE=$(curl --silent --fail -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG_NAME")

          if [ -z "$RELEASE" ]; then
            echo "No release exists for tag $TAG_NAME"
            exit 1
          else
            echo "Release exists for tag $TAG_NAME"
          fi

# jobs:
#   get_tags:
#     runs-on: ubuntu-latest
#     outputs:
#       commit_hash: ${{ steps.get_commit.outputs.commit_hash }}

#     steps:
#       - name: Get All Tags
#         id: get_tags
#         run: |
#           # Get all tags and store them in a variable
#           tags=$(git tag)
#           echo "Tags found: $tags"
#           echo "::set-output name=tags::$tags"

#       - name: Filter Tags by Regex
#         id: filter_tags
#         run: |
#           # Define the regex pattern
#           regex=""